/*
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-FileCopyrightText: Huawei Inc.
 */

package org.eclipse.xpanse.terraform.boot.models.response;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import java.util.Map;
import lombok.Builder;
import lombok.Data;
import org.eclipse.xpanse.terraform.boot.models.enums.DeploymentScenario;

/**
 * Data model for the Terraform command execution results.
 */
@Data
@Builder
public class TerraformResult {

    @Schema(description = "This value can be set by the client if they wish to know the type of"
            + "request for which the callback response is generated from terraform-boot. There will"
            + "be no difference in the way request is executed. This information is only set in"
            + "the callback response again for the client to handle the callback response"
            + "accordingly.")
    private DeploymentScenario deploymentScenario;
    @Schema(description = "defines if the command was successfully executed")
    @NotNull
    private boolean isCommandSuccessful;
    @Schema(description = "stdout of the command returned as string.")
    private String commandStdOutput;
    @Schema(description = "stderr of the command returned as string.")
    private String commandStdError;
    @Schema(description = ".tfstate file contents returned as string.")
    private String terraformState;
    @Schema(description = "Data of all other files generated by the terraform execution."
            + "The map key contains the file name and value is the file contents as string.")
    private Map<String, String> importantFileContentMap;
}
