/*
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-FileCopyrightText: Huawei Inc.
 */

package org.eclipse.xpanse.terraform.boot.models.response;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import java.util.Map;
import lombok.Builder;
import lombok.Data;
import org.eclipse.xpanse.terraform.boot.models.enums.DestroyScenario;

/**
 * Data model for the Terraform command execution results.
 */
@Data
@Builder
public class TerraformResult {

    @Schema(description =
            "This value is set only if the same is set in the request as well. This is useful only"
                    + " for the caller to differentiate what type of destroy it is. No difference"
                    + " in the way destroy will be executed."
                    + "based on this flag. User may use this flag in case callback are used. "
                    + "So the calling application can know "
                    + "the result is for which specific destroy use case within the "
                    + "calling system.")
    private DestroyScenario destroyScenario;
    @Schema(description = "defines if the command was successfully executed")
    @NotNull
    private boolean isCommandSuccessful;
    @Schema(description = "stdout of the command returned as string.")
    private String commandStdOutput;
    @Schema(description = "stderr of the command returned as string.")
    private String commandStdError;
    @Schema(description = ".tfstate file contents returned as string.")
    private String terraformState;
    @Schema(description = "Data of all other files generated by the terraform execution."
            + "The map key contains the file name and value is the file contents as string.")
    private Map<String, String> importantFileContentMap;
}
