#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#
name: terra-boot-ci

# Run this workflow every time a new commit push to the repository
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Format check
        run: mvn spotless:check &&  mvn checkstyle:check
      - name: Build & Test
        run: mvn --batch-mode --update-snapshots --no-transfer-progress verify
